# Generated by Django 6.0.2 on 2026-03-09 14:38

import audits.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audit_type', models.CharField(choices=[('interna', 'Interna'), ('externa', 'Externa')], max_length=20)),
                ('area', models.CharField(max_length=150)),
                ('objective', models.TextField(blank=True, default='')),
                ('planned_date', models.DateField()),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('programada', 'Programada'), ('en_proceso', 'En proceso'), ('cerrada', 'Cerrada')], default='programada', max_length=20)),
                ('responsible_area', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_as_auditor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='AuditCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='audits.audit')),
            ],
            options={
                'ordering': ('item_number',),
                'unique_together': {('audit', 'item_number')},
            },
        ),
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('cumple', 'Cumple'), ('no_cumple', 'No cumple'), ('observacion', 'Observación')], max_length=20)),
                ('observation', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('criterion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='audits.auditcriterion')),
            ],
        ),
        migrations.CreateModel(
            name='NonConformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nc_type', models.CharField(choices=[('mayor', 'Mayor'), ('menor', 'Menor'), ('observacion', 'Observación')], max_length=20)),
                ('description', models.TextField()),
                ('evidence_text', models.TextField(blank=True, default='')),
                ('responsible', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('abierta', 'Abierta'), ('en_proceso', 'En proceso'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_conformities', to='audits.audit')),
                ('criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_conformities', to='audits.auditcriterion')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause', models.TextField()),
                ('immediate_action', models.TextField()),
                ('permanent_action', models.TextField()),
                ('evidence', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('non_conformity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_action', to='audits.nonconformity')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=audits.models.audit_evidence_upload_to)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='audits.audit')),
                ('non_conformity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='audits.nonconformity')),
            ],
        ),
    ]
