# Generated by Django 6.0.2 on 2026-03-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditresult',
            name='criterion',
        ),
        migrations.RenameField(
            model_name='nonconformity',
            old_name='evidence_text',
            new_name='evidence',
        ),
        migrations.AddField(
            model_name='auditcriterion',
            name='observation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auditcriterion',
            name='result',
            field=models.CharField(choices=[('cumple', 'Cumple'), ('no_cumple', 'No cumple'), ('observacion', 'Observación')], default='observacion', max_length=20),
        ),
        migrations.AlterField(
            model_name='audit',
            name='auditor',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.DeleteModel(
            name='AuditEvidence',
        ),
        migrations.DeleteModel(
            name='AuditResult',
        ),
    ]
