# Generated by Django 6.0.2 on 2026-02-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='', verbose_name='documents/'),
        ),
    ]
