# Generated by Django 6.0.2 on 2026-03-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together={('project', 'test_case', 'name')},
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='version',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='directory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='directory',
            name='slug',
        ),
    ]
